import { instrument } from "@socket.io/admin-ui";
import { NextFunction, Request, Response } from "express";
import { Server } from "socket.io";
import server, { sessionMiddleware } from "../app";
import { logger } from "../../logger";
import { RoomSession } from "../../types/Session";
import { getUserRoomSession } from "../session/session.handler";
import redisClient from "./redis";
import { io } from "../app";
import { exitRoom, exitRoomFunction } from "../room/room.handler";
import { MessageInterface } from "../../types/Message";
